services:
  ai-deep-research-mcp:
    build: .
    container_name: ai-deep-research-mcp
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - MCP_LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; print('🎓 Educational MCP Server healthy!')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: mcp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - ai-deep-research-mcp
    restart: unless-stopped
